# Generated by Django 6.0.4 on 2026-04-30 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymember',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm.company'),
        ),
        migrations.AddField(
            model_name='companymember',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='assigned_members', to='crm.project'),
        ),
        migrations.AddField(
            model_name='companymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='crm.company'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='crm.company'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='crm.company'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='auth_app.role'),
        ),
        migrations.AddField(
            model_name='companymember',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='auth_app.role'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='companymember',
            unique_together={('user', 'company')},
        ),
    ]
