# Generated by Django 6.0.4 on 2026-04-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='role',
            name='company',
        ),
    ]
