# Generated by Django 6.0.4 on 2026-05-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='agni_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
