# Generated by Django 6.0.4 on 2026-04-29 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_project_lead_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ghl_pipeline_id',
            new_name='external_pipeline_id',
        ),
    ]
