# Generated by Django 6.0.4 on 2026-04-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_ghl_pipeline_id_project_external_pipeline_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymember',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='assigned_members', to='crm.project'),
        ),
    ]
