# Generated by Codex on 2026-04-30

from django.db import migrations


DEFAULT_PERMISSIONS = [
    ("company.view", "View company details"),
    ("company.edit", "Edit company details"),
    ("leads.view", "View leads"),
    ("analytics.view", "View analytics"),
    ("projects.view", "View projects"),
    ("projects.manage", "Create/update projects"),
    ("members.view", "View company members"),
    ("members.manage", "Create/update members and assignments"),
    ("roles.view", "View roles"),
    ("roles.manage", "Create/update roles and permissions"),
    ("permissions.view", "View permission catalog"),
    ("invitations.view", "View invitations"),
    ("invitations.manage", "Create/manage invitations"),
    ("join_requests.view", "View join requests"),
    ("join_requests.manage", "Approve/reject join requests"),
    ("integrations.view", "View CRM integrations status"),
    ("integrations.manage", "Connect/manage CRM integrations"),
    ("sync.trigger", "Trigger CRM sync"),
]


def seed_permissions(apps, schema_editor):
    Permission = apps.get_model("crm", "Permission")
    Role = apps.get_model("crm", "Role")

    for code, description in DEFAULT_PERMISSIONS:
        Permission.objects.update_or_create(code=code, defaults={"description": description})

    all_perm_ids = list(Permission.objects.values_list("id", flat=True))
    if all_perm_ids:
        admin_roles = Role.objects.filter(name="Admin")
        for role in admin_roles:
            role.permissions.set(all_perm_ids)


def unseed_permissions(apps, schema_editor):
    Permission = apps.get_model("crm", "Permission")
    codes = [c for c, _ in DEFAULT_PERMISSIONS]
    Permission.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_companymember_projects"),
    ]

    operations = [
        migrations.RunPython(seed_permissions, reverse_code=unseed_permissions),
    ]

